package javaapplication1;


import com.placeholder.PlaceHolder;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Faizan Ali
 */
public class AddOrSee extends javax.swing.JFrame {
    
PlaceHolder holder;
Connection con=null;
Statement stmt;

    /**
     * Creates new form AddOrSee
     */
    public AddOrSee() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        

        adminname.setText("Hello "+LoginSession.username);
   
        holder = new PlaceHolder(userid, "Enter UserName");
        
        
        adminname.setFocusable(false);
//        adminname.setText("Hello Mr. Admin");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Addchild = new javax.swing.JLabel();
        addhere = new javax.swing.JLabel();
        fetch_user = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        userid = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        adminname = new javax.swing.JLabel();
        jLabelMinimize1 = new javax.swing.JLabel();
        jLabelClose1 = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(43, 57, 144));
        jPanel1.setPreferredSize(new java.awt.Dimension(870, 480));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Addchild.setFont(new java.awt.Font("Gotham Light", 1, 14)); // NOI18N
        Addchild.setForeground(new java.awt.Color(255, 255, 255));
        Addchild.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Addchild.setText("Add Here");
        Addchild.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Addchild.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddchildMouseClicked(evt);
            }
        });
        jPanel1.add(Addchild, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 360, 160, 40));

        addhere.setFont(new java.awt.Font("Gotham Light", 1, 14)); // NOI18N
        addhere.setForeground(new java.awt.Color(255, 255, 255));
        addhere.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addhere.setIcon(new javax.swing.ImageIcon(getClass().getResource("/All the Images/btn ai1.png"))); // NOI18N
        addhere.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addhereMouseClicked(evt);
            }
        });
        jPanel1.add(addhere, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 360, 160, 40));

        fetch_user.setFont(new java.awt.Font("Gotham Light", 1, 14)); // NOI18N
        fetch_user.setForeground(new java.awt.Color(255, 255, 255));
        fetch_user.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fetch_user.setText("Click Here");
        fetch_user.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fetch_user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fetch_userMouseClicked(evt);
            }
        });
        jPanel1.add(fetch_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 400, 160, 40));

        jLabel7.setFont(new java.awt.Font("Gotham Light", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/All the Images/btn ai1.png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 400, 160, 40));

        jLabel8.setFont(new java.awt.Font("Gotham Light", 0, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Enter UserID here");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 220, 40));

        userid.setFont(new java.awt.Font("Gotham Light", 0, 14)); // NOI18N
        userid.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        userid.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        userid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                useridActionPerformed(evt);
            }
        });
        userid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                useridKeyTyped(evt);
            }
        });
        jPanel1.add(userid, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 220, 30));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 380, 220, 10));

        adminname.setFont(new java.awt.Font("Gotham Medium", 0, 26)); // NOI18N
        adminname.setForeground(new java.awt.Color(255, 255, 255));
        adminname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        adminname.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(adminname, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 330, 50));

        jLabelMinimize1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/All the Images/min-sqr.png"))); // NOI18N
        jLabelMinimize1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMinimize1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinimize1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabelMinimize1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 10, -1, 60));

        jLabelClose1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/All the Images/close-sqr.png"))); // NOI18N
        jLabelClose1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelClose1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelClose1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabelClose1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 10, -1, 60));

        logout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/All the Images/close.png"))); // NOI18N
        logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });
        jPanel1.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 130, 40));

        jLabel9.setFont(new java.awt.Font("Gotham Light", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Logout");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 70, 40));

        jLabel1.setFont(new java.awt.Font("Gotham Medium", 0, 11)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/All the Images/Admin First.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 850, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void useridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_useridActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_useridActionPerformed

    private void useridKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_useridKeyTyped

    }//GEN-LAST:event_useridKeyTyped

    private void addhereMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addhereMouseClicked
//           ChildRegistration object = new ChildRegistration();
//           object.pack();
//           object.setVisible(true);
//           object.setLocationRelativeTo(null);
//           object.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
//           this.dispose();
    }//GEN-LAST:event_addhereMouseClicked

    private void jLabelMinimize1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinimize1MouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelMinimize1MouseClicked

    private void jLabelClose1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelClose1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabelClose1MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseClicked

    private void fetch_userMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fetch_userMouseClicked
            String id = userid.getText();
            
            try{
                    String query="SELECT * FROM `child_details` WHERE `child_ID`='"+id+"'";
                    con = DriverManager.getConnection("jdbc:mysql://localhost/child e-immunization","root","");  
                    stmt = con.createStatement();
                    ResultSet rs = stmt.executeQuery(query); 

                    if (rs.next()) {
                            ChildSession.username = rs.getString("child_ID");
                            ViewDetailOfChild object = new ViewDetailOfChild();
                            object.setVisible(true);
                            this.dispose();
                    }
                            
                    else{
                            userid.setText("");
                            JOptionPane.showMessageDialog(this, "Please Enter valid UserID of Child ..", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                    con.close();
                    stmt.close();
            }
            catch(Exception ex){
                    JOptionPane.showMessageDialog(this, "Oop's Something went wrong ..", "Error", JOptionPane.ERROR_MESSAGE);          
            }
    }//GEN-LAST:event_fetch_userMouseClicked

    private void AddchildMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddchildMouseClicked
        // TODO add your handling code here:
        
        ChildRegistration object = new ChildRegistration();
           object.pack();
           object.setVisible(true);
           object.setLocationRelativeTo(null);
           object.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
           this.dispose();
    }//GEN-LAST:event_AddchildMouseClicked

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        // TODO add your handling code here:

        AdminSignUp ob = new AdminSignUp();
        ob.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddOrSee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddOrSee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddOrSee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddOrSee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddOrSee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Addchild;
    private javax.swing.JLabel addhere;
    private javax.swing.JLabel adminname;
    private javax.swing.JLabel fetch_user;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelClose1;
    private javax.swing.JLabel jLabelMinimize1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JLabel logout;
    private javax.swing.JTextField userid;
    // End of variables declaration//GEN-END:variables
}
