package javaapplication1;


import com.placeholder.PlaceHolder;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Faizan Ali
 */
public class AdminRegistration extends javax.swing.JFrame {
    
    Connection con=null;
    PreparedStatement pst;
    PlaceHolder holder;
    /**
     * Creates new form SignUp
     */
    public AdminRegistration() {
        initComponents();
        checkFormIsEmpty();
        this.setLocationRelativeTo(null);
        
        holder = new PlaceHolder(firstname, "First Name");          
        holder = new PlaceHolder(lastname, "Last Name");        
        holder = new PlaceHolder(phone, "Phone Number");        
        holder = new PlaceHolder(email, "Email Address");        
        holder = new PlaceHolder(address, "Address");        
        holder = new PlaceHolder(regId, "User Name");        
        holder = new PlaceHolder(password, "Password");        
      
        holder = new PlaceHolder(confirmpassword, "Confirm Paasword");

//        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }
    
    private boolean checkFormIsEmpty(){
        if(firstname.getText().isEmpty()|lastname.getText().isEmpty()|email.getText().isEmpty()|phone.getText().isEmpty()|address.getText().isEmpty()|regId.getText().isEmpty()|password.getText().isEmpty()|confirmpassword.getText().isEmpty()){
            return true;
        }
        else{
            return false;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        firstname = new javax.swing.JTextField();
        lastname = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        email = new javax.swing.JTextField();
        phone = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        regId = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        loginbtn = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        female = new javax.swing.JRadioButton();
        male = new javax.swing.JRadioButton();
        loginbtn1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabelMinimize = new javax.swing.JLabel();
        jLabelClose = new javax.swing.JLabel();
        showpassword = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        confirmpassword = new javax.swing.JPasswordField();
        password = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(43, 57, 144));
        jPanel1.setPreferredSize(new java.awt.Dimension(854, 480));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 200, 10));

        firstname.setFont(new java.awt.Font("Gotham Light", 0, 14)); // NOI18N
        firstname.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        firstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstnameActionPerformed(evt);
            }
        });
        jPanel1.add(firstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 200, 30));

        lastname.setFont(new java.awt.Font("Gotham Light", 0, 14)); // NOI18N
        lastname.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        lastname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastnameActionPerformed(evt);
            }
        });
        jPanel1.add(lastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 200, 30));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 200, 10));

        email.setFont(new java.awt.Font("Gotham Light", 0, 14)); // NOI18N
        email.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        jPanel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, 200, 30));

        phone.setFont(new java.awt.Font("Gotham Light", 0, 14)); // NOI18N
        phone.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneActionPerformed(evt);
            }
        });
        jPanel1.add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 200, 30));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 200, 10));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, 200, 10));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 330, 200, 10));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, 200, 10));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, 200, 10));

        regId.setFont(new java.awt.Font("Gotham Light", 0, 14)); // NOI18N
        regId.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        regId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regIdActionPerformed(evt);
            }
        });
        jPanel1.add(regId, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 200, 30));

        address.setFont(new java.awt.Font("Gotham Light", 0, 14)); // NOI18N
        address.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressActionPerformed(evt);
            }
        });
        jPanel1.add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, 200, 30));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, 200, 10));

        loginbtn.setFont(new java.awt.Font("Gotham Light", 1, 14)); // NOI18N
        loginbtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginbtn.setText("Login");
        loginbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginbtnMouseClicked(evt);
            }
        });
        jPanel1.add(loginbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 380, 160, 40));

        jLabel4.setFont(new java.awt.Font("Gotham Light", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/All the Images/btn white.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 380, 180, 40));

        female.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(female);
        female.setFont(new java.awt.Font("Gotham", 0, 14)); // NOI18N
        female.setText("Female");
        female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleActionPerformed(evt);
            }
        });
        jPanel1.add(female, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, -1, -1));

        male.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(male);
        male.setFont(new java.awt.Font("Gotham", 0, 14)); // NOI18N
        male.setText("Male");
        male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleActionPerformed(evt);
            }
        });
        jPanel1.add(male, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, -1, -1));

        loginbtn1.setFont(new java.awt.Font("Gotham Light", 1, 14)); // NOI18N
        loginbtn1.setForeground(new java.awt.Color(255, 255, 255));
        loginbtn1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginbtn1.setText("Registration");
        loginbtn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginbtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginbtn1MouseClicked(evt);
            }
        });
        jPanel1.add(loginbtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 370, 160, 40));

        jLabel5.setFont(new java.awt.Font("Gotham Light", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/All the Images/btn ai1.png"))); // NOI18N
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 370, 180, 40));

        jLabelMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/All the Images/min-sqr.png"))); // NOI18N
        jLabelMinimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinimizeMouseClicked(evt);
            }
        });
        jPanel1.add(jLabelMinimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 10, -1, 60));

        jLabelClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/All the Images/close-sqr.png"))); // NOI18N
        jLabelClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseClicked(evt);
            }
        });
        jPanel1.add(jLabelClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 10, -1, 60));

        showpassword.setBackground(new java.awt.Color(255, 255, 255));
        showpassword.setFont(new java.awt.Font("Gotham Light", 0, 12)); // NOI18N
        showpassword.setForeground(new java.awt.Color(255, 255, 255));
        showpassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        showpassword.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        showpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showpasswordActionPerformed(evt);
            }
        });
        jPanel1.add(showpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 340, -1, 20));

        jLabel3.setFont(new java.awt.Font("Gotham Light", 0, 12)); // NOI18N
        jLabel3.setText("Show Password");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 330, -1, 40));

        jLabel2.setFont(new java.awt.Font("Gotham", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Click here if already have Account");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 340, 260, 40));

        confirmpassword.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        confirmpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmpasswordActionPerformed(evt);
            }
        });
        jPanel1.add(confirmpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, 200, 30));

        password.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        jPanel1.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, 200, 30));

        jLabel1.setFont(new java.awt.Font("Gotham Medium", 0, 11)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/All the Images/registration1.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 0, 910, 480));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void firstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstnameActionPerformed

    private void lastnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastnameActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneActionPerformed

    private void regIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regIdActionPerformed

    private void addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressActionPerformed

    private void maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleActionPerformed
        // TODO add your handling code here:
        gender="male";
    }//GEN-LAST:event_maleActionPerformed

    private void loginbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginbtnMouseClicked
           AdminSignUp object = new AdminSignUp();
           object.pack();
           object.setVisible(true);
           object.setLocationRelativeTo(null);
           object.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
           this.dispose();
    }//GEN-LAST:event_loginbtnMouseClicked

    private void loginbtn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginbtn1MouseClicked
        // TODO add your handling code here:
        String firstname1 = firstname.getText();
        String lastname1 = lastname.getText();
        String email1 = email.getText();
        String phone1 = phone.getText();
        String address1 = address.getText();
        String regId1 = regId.getText();
        String password1 = password.getText();
        String confirmpassword1 = confirmpassword.getText();
        
    
        try{
            String query="INSERT INTO `registration_login`(`first_name`, `last_name`, `reg_email`, `reg_phone`, `reg_address`, `reg_gender`, `reg_username`, `password`, `confirm_password`) VALUES (?,?,?,?,?,?,?,?,?)";
            con=DriverManager.getConnection("jdbc:mysql://localhost/child e-immunization","root","");  
            pst=con.prepareStatement(query);
            pst.setString(1, firstname1);
            pst.setString(2, lastname1);
            pst.setString(3, email1);
            pst.setString(4, phone1);
            pst.setString(5, address1);
            pst.setString(6, gender);
            pst.setString(7, regId1);
            pst.setString(8, password1);
            pst.setString(9, confirmpassword1);

            if(checkFormIsEmpty()){
                JOptionPane.showMessageDialog(this, "Field should not be empty ", "Empty Field", JOptionPane.ERROR_MESSAGE);
            }
            else{
                if(password1.equals(confirmpassword1)){
                    pst.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Details Added Sucessfully", "Success", JOptionPane.INFORMATION_MESSAGE);
                    AdminSignUp ob = new AdminSignUp();
                    ob.setVisible(true);
                    this.setVisible(false);
                }
                else{
                    JOptionPane.showMessageDialog(this, "Password is not matching ", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
            
            
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this,"Oop's Somethig went wrong", "Error", JOptionPane.ERROR_MESSAGE);           
        }
    }//GEN-LAST:event_loginbtn1MouseClicked

    private void jLabelMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinimizeMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelMinimizeMouseClicked

    private void jLabelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabelCloseMouseClicked

    private void femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleActionPerformed
        // TODO add your handling code here:
            gender="female";
    }//GEN-LAST:event_femaleActionPerformed

    private void showpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showpasswordActionPerformed
        if(showpassword.isSelected()){
            password.setEchoChar((char)0);
            confirmpassword.setEchoChar((char)0);
        }
        else{
            password.setEchoChar('*');
            confirmpassword.setEchoChar('*');
        }
    }//GEN-LAST:event_showpasswordActionPerformed

    private void confirmpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmpasswordActionPerformed

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminRegistration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPasswordField confirmpassword;
    private javax.swing.JTextField email;
    private javax.swing.JRadioButton female;
    private javax.swing.JTextField firstname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelClose;
    private javax.swing.JLabel jLabelMinimize;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTextField lastname;
    private javax.swing.JLabel loginbtn;
    private javax.swing.JLabel loginbtn1;
    private javax.swing.JRadioButton male;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField phone;
    private javax.swing.JTextField regId;
    private javax.swing.JCheckBox showpassword;
    // End of variables declaration//GEN-END:variables
    private String gender;
}
