package javaapplication1;

import com.placeholder.PlaceHolder;
import java.awt.TextField;
import java.sql.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Faizan Ali
 */
public class AdminSignUp extends javax.swing.JFrame {

    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    PlaceHolder holder;

    /**
     * Creates new form SignUp
     */
    public AdminSignUp() {
        initComponents();
        checkFormIsEmpty();
        this.setLocationRelativeTo(null);

        holder = new PlaceHolder(regId, "UserName");
        holder = new PlaceHolder(password, "Password");

//        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    private boolean checkFormIsEmpty() {
        if (regId.getText().isEmpty() | password.getText().isEmpty()) {
            return true;
        } else {
            return false;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        regId = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        showpassword = new javax.swing.JCheckBox();
        password = new javax.swing.JPasswordField();
        jSeparator6 = new javax.swing.JSeparator();
        clickhere = new javax.swing.JLabel();
        forgetpassword = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabelMinimize = new javax.swing.JLabel();
        jLabelClose = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(43, 57, 144));
        jPanel1.setPreferredSize(new java.awt.Dimension(870, 480));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        regId.setFont(new java.awt.Font("Gotham Light", 0, 14)); // NOI18N
        regId.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        regId.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        regId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regIdActionPerformed(evt);
            }
        });
        jPanel1.add(regId, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 150, 220, 30));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 180, 220, 10));

        jLabel2.setFont(new java.awt.Font("Gotham Light", 0, 12)); // NOI18N
        jLabel2.setText("Show Password");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 240, -1, 40));

        showpassword.setBackground(new java.awt.Color(255, 255, 255));
        showpassword.setFont(new java.awt.Font("Gotham Light", 0, 12)); // NOI18N
        showpassword.setForeground(new java.awt.Color(255, 255, 255));
        showpassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        showpassword.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        showpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showpasswordActionPerformed(evt);
            }
        });
        jPanel1.add(showpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 250, -1, 20));

        password.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        jPanel1.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 210, 220, 30));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 240, 220, 10));

        clickhere.setFont(new java.awt.Font("Gotham Light", 0, 14)); // NOI18N
        clickhere.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        clickhere.setText("Create Account");
        clickhere.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clickhere.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickhereMouseClicked(evt);
            }
        });
        jPanel1.add(clickhere, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 320, 190, 20));

        forgetpassword.setFont(new java.awt.Font("Gotham Light", 0, 14)); // NOI18N
        forgetpassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        forgetpassword.setText("Forget Password ?");
        forgetpassword.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        forgetpassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                forgetpasswordMouseClicked(evt);
            }
        });
        jPanel1.add(forgetpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 290, 190, 20));

        jLabel5.setFont(new java.awt.Font("Gotham Light", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Login");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 350, 160, 40));

        jLabel4.setFont(new java.awt.Font("Gotham Light", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/All the Images/btn ai1.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 350, 160, 40));

        jLabelMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/All the Images/min-sqr.png"))); // NOI18N
        jLabelMinimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinimizeMouseClicked(evt);
            }
        });
        jPanel1.add(jLabelMinimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 10, -1, 60));

        jLabelClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/All the Images/close-sqr.png"))); // NOI18N
        jLabelClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseClicked(evt);
            }
        });
        jPanel1.add(jLabelClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 10, -1, 60));

        jLabel1.setFont(new java.awt.Font("Gotham Medium", 0, 11)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/All the Images/First1.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 480));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void clickhereMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clickhereMouseClicked
        AdminRegistration object = new AdminRegistration();
        object.pack();
        object.setVisible(true);
        object.setLocationRelativeTo(null);
        object.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_clickhereMouseClicked

    private void forgetpasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgetpasswordMouseClicked

    }//GEN-LAST:event_forgetpasswordMouseClicked

    private void regIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regIdActionPerformed

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    private void showpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showpasswordActionPerformed
        if (showpassword.isSelected()) {
            password.setEchoChar((char) 0);
        } else {
            password.setEchoChar('*');
        }
    }//GEN-LAST:event_showpasswordActionPerformed

    private void jLabelMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinimizeMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelMinimizeMouseClicked

    private void jLabelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabelCloseMouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:

        String sql = "select * from registration_login where reg_username=? and password=?";

        String regId1 = regId.getText();
        String password1 = password.getText();

        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost/child e-immunization", "root", "");

            pst = con.prepareStatement(sql);
            pst.setString(1, regId1);
            pst.setString(2, password1);
                        
            rs = pst.executeQuery();
            
            

            if (checkFormIsEmpty()) {
                JOptionPane.showMessageDialog(this, "Field should not be empty ", "Empty Field", JOptionPane.ERROR_MESSAGE);
            }
            else{
                    
                    if (rs.next()) {
                        String username = rs.getString("first_name");
                        LoginSession.username = username;
                        AddOrSee object = new AddOrSee();
                        object.pack();
                        object.setVisible(true);
                        object.setLocationRelativeTo(null);
                        object.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                        this.dispose();
                    } 
                    else {
                        JOptionPane.showMessageDialog(this, "Please Enter valid UserID or Password ..", "Error", JOptionPane.ERROR_MESSAGE);
                    }
            }
        }catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Oop's Something went wrong ..", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jLabel5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminSignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel clickhere;
    private javax.swing.JLabel forgetpassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelClose;
    private javax.swing.JLabel jLabelMinimize;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField regId;
    private javax.swing.JCheckBox showpassword;
    // End of variables declaration//GEN-END:variables
}
