package javaapplication1;


import com.placeholder.PlaceHolder;
import javax.swing.JFrame;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Faizan Ali
 */
public class ChildRegistration extends javax.swing.JFrame {
    
    Connection con=null;
    PreparedStatement pst;
    PlaceHolder holder;
    /**
     * Creates new form SignUp
     */
    public ChildRegistration() {
        this.pst = null;
        initComponents();
        this.setLocationRelativeTo(null);
        
        holder = new PlaceHolder(fullname, "Full Name");          
        holder = new PlaceHolder(mothername, "Mother Name");        
        holder = new PlaceHolder(mailaddress, "Mail Address");        
        holder = new PlaceHolder(userid, "User Id");        
        holder = new PlaceHolder(age, "Child Age");
        holder = new PlaceHolder(weight, "Child Weight");
        holder = new PlaceHolder(height, "Child Height");

//        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        fullname = new javax.swing.JTextField();
        mothername = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        mailaddress = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        userid = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        goback1 = new javax.swing.JLabel();
        goback = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        female = new javax.swing.JRadioButton();
        male = new javax.swing.JRadioButton();
        height = new javax.swing.JTextField();
        jSeparator11 = new javax.swing.JSeparator();
        weight = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        age = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        addChildbtn = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabelClose1 = new javax.swing.JLabel();
        jLabelMinimize1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(43, 57, 144));
        jPanel1.setPreferredSize(new java.awt.Dimension(854, 480));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Gotham", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Go Back to Admin Panel");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 275, 280, 40));

        jComboBox1.setFont(new java.awt.Font("Gotham", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vaccine Name", "BCG", "DTP 1", "DTP 2", "Hepatitis A", "MMR 1", "MMR 2", "InfluenzaOPV" }));
        jComboBox1.setBorder(null);
        jComboBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 200, 30));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 200, 10));

        fullname.setFont(new java.awt.Font("Gotham Light", 0, 14)); // NOI18N
        fullname.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        fullname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fullnameActionPerformed(evt);
            }
        });
        jPanel1.add(fullname, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 200, 30));

        mothername.setFont(new java.awt.Font("Gotham Light", 0, 14)); // NOI18N
        mothername.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        mothername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mothernameActionPerformed(evt);
            }
        });
        jPanel1.add(mothername, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 200, 30));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 200, 10));

        mailaddress.setFont(new java.awt.Font("Gotham Light", 0, 14)); // NOI18N
        mailaddress.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        mailaddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mailaddressActionPerformed(evt);
            }
        });
        jPanel1.add(mailaddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 200, 30));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 200, 10));

        userid.setFont(new java.awt.Font("Gotham Light", 0, 14)); // NOI18N
        userid.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        userid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                useridActionPerformed(evt);
            }
        });
        jPanel1.add(userid, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, 200, 30));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, 200, 10));

        goback1.setFont(new java.awt.Font("Gotham Light", 1, 14)); // NOI18N
        goback1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        goback1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/All the Images/goback.png"))); // NOI18N
        goback1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        goback1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                goback1MouseClicked(evt);
            }
        });
        jPanel1.add(goback1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 330, 60, 40));

        goback.setFont(new java.awt.Font("Gotham Light", 1, 14)); // NOI18N
        goback.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        goback.setText("Go Back");
        goback.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        goback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gobackMouseClicked(evt);
            }
        });
        jPanel1.add(goback, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 330, 70, 40));

        jLabel4.setFont(new java.awt.Font("Gotham Light", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/All the Images/btn white.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 330, 180, 40));

        female.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(female);
        female.setFont(new java.awt.Font("Gotham", 0, 14)); // NOI18N
        female.setText("Female");
        female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleActionPerformed(evt);
            }
        });
        jPanel1.add(female, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, -1, -1));

        male.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(male);
        male.setFont(new java.awt.Font("Gotham", 0, 14)); // NOI18N
        male.setText("Male");
        male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleActionPerformed(evt);
            }
        });
        jPanel1.add(male, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, -1, -1));

        height.setFont(new java.awt.Font("Gotham Light", 0, 14)); // NOI18N
        height.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        height.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                heightActionPerformed(evt);
            }
        });
        jPanel1.add(height, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, 130, 30));
        jPanel1.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 330, 130, 10));

        weight.setFont(new java.awt.Font("Gotham Light", 0, 14)); // NOI18N
        weight.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        weight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weightActionPerformed(evt);
            }
        });
        jPanel1.add(weight, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, 140, 30));
        jPanel1.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, 140, 10));

        age.setFont(new java.awt.Font("Gotham Light", 0, 14)); // NOI18N
        age.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageActionPerformed(evt);
            }
        });
        jPanel1.add(age, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, 130, 30));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, 130, 10));

        addChildbtn.setFont(new java.awt.Font("Gotham Light", 1, 14)); // NOI18N
        addChildbtn.setForeground(new java.awt.Color(255, 255, 255));
        addChildbtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addChildbtn.setText("Add");
        addChildbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addChildbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addChildbtnMouseClicked(evt);
            }
        });
        jPanel1.add(addChildbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 370, 160, 40));

        jLabel5.setFont(new java.awt.Font("Gotham Light", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/All the Images/btn ai1.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 370, 180, 40));

        jLabelClose1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/All the Images/close-sqr.png"))); // NOI18N
        jLabelClose1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelClose1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelClose1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabelClose1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 10, -1, 60));

        jLabelMinimize1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/All the Images/min-sqr.png"))); // NOI18N
        jLabelMinimize1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMinimize1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinimize1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabelMinimize1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 10, -1, 60));

        jLabel1.setFont(new java.awt.Font("Gotham Medium", 0, 11)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/All the Images/AddChildDetails.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 0, 910, 480));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void fullnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fullnameActionPerformed

    private void mailaddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mailaddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mailaddressActionPerformed

    private void useridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_useridActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_useridActionPerformed

    private void maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleActionPerformed
        gender="male";
    }//GEN-LAST:event_maleActionPerformed

    private void addChildbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addChildbtnMouseClicked
        try{
            String query="INSERT INTO `child_details`(`child_ID`, `child_name`, `mail_address`, `mother_name`, `child_gender`, `child_birth`, `child_age`, `child_weight`, `child_height`, `child_vaccines`) VALUES (?,?,?,?,?,?,?,?,?,?)";
            con=DriverManager.getConnection("jdbc:mysql://localhost/child e-immunization","root","");  
            pst=con.prepareStatement(query);
            pst.setString(1, userid.getText());
            pst.setString(2, fullname.getText());
            pst.setString(3, mailaddress.getText());
            pst.setString(4, mothername.getText());
            pst.setString(5, gender);
            //pst.setString(6, ((JTextField)jDateChooser1.getDateEditor().getUiComponent()).getText());
            pst.setString(7, age.getText());
            pst.setString(8, weight.getText());
            pst.setString(9, height.getText());
            pst.setString(10, jComboBox1.getSelectedItem().toString());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Details added successfully ..");
            
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, "Please Enter Valid Information ..", "Congratulations", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_addChildbtnMouseClicked

    private void ageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageActionPerformed

    private void weightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_weightActionPerformed

    private void heightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_heightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_heightActionPerformed

    private void mothernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mothernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mothernameActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void gobackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gobackMouseClicked
        AddOrSee object = new AddOrSee();
        object.pack();
        object.setVisible(true);
        object.setLocationRelativeTo(null);
        object.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_gobackMouseClicked

    private void goback1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goback1MouseClicked
        AddOrSee object = new AddOrSee();
        object.pack();
        object.setVisible(true);
        object.setLocationRelativeTo(null);
        object.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_goback1MouseClicked

    private void jLabelClose1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelClose1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabelClose1MouseClicked

    private void jLabelMinimize1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinimize1MouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelMinimize1MouseClicked

    private void femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleActionPerformed
       gender="female";
    }//GEN-LAST:event_femaleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChildRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChildRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChildRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChildRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChildRegistration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addChildbtn;
    private javax.swing.JTextField age;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton female;
    private javax.swing.JTextField fullname;
    private javax.swing.JLabel goback;
    private javax.swing.JLabel goback1;
    private javax.swing.JTextField height;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelClose1;
    private javax.swing.JLabel jLabelMinimize1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField mailaddress;
    private javax.swing.JRadioButton male;
    private javax.swing.JTextField mothername;
    private javax.swing.JTextField userid;
    private javax.swing.JTextField weight;
    // End of variables declaration//GEN-END:variables
    private String gender;
}
