/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication1;

import com.placeholder.PlaceHolder;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Faizan Ali
 */
public class EditChildDetails extends javax.swing.JFrame {

    Connection con=null;
    Statement stmt;
    PreparedStatement pst;

    /**
     * Creates new form EditChildDetails
     */
    public EditChildDetails() {
        initComponents();
        showDetails();
        changeVaccine.setVisible(false);
    }

    private void showDetails(){
        String id = ChildSession.username;
        try{
            String query="SELECT * FROM `child_details` WHERE `child_ID`='"+id+"'";
            con = DriverManager.getConnection("jdbc:mysql://localhost/child e-immunization","root","");  
            stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery(query); 
            
            while (rs.next()) {
                    userid.setText(rs.getString(1));
                    childfullname.setText(rs.getString(2));
                    mail_id.setText(rs.getString(3));
                    mothername.setText(rs.getString(4));
                    dob.setText(rs.getString(6));
                    age.setText(rs.getString(7));
                    weight.setText(rs.getString(8));
                    height.setText(rs.getString(9));
                    gender.setText(rs.getString(5));
                    vaccine.setText(rs.getString(10));             
            }            
            }catch(Exception ex){
                JOptionPane.showMessageDialog(null,ex);          
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        save = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelMinimize1 = new javax.swing.JLabel();
        jLabelClose1 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        goback = new javax.swing.JLabel();
        goback1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        childfullname = new javax.swing.JTextField();
        mail_id = new javax.swing.JTextField();
        mothername = new javax.swing.JTextField();
        userid = new javax.swing.JTextField();
        changevaccine = new javax.swing.JButton();
        vaccine = new javax.swing.JTextField();
        height = new javax.swing.JTextField();
        weight = new javax.swing.JTextField();
        age = new javax.swing.JTextField();
        dob = new javax.swing.JTextField();
        gender = new javax.swing.JTextField();
        changeVaccine = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(43, 57, 144));
        jPanel1.setPreferredSize(new java.awt.Dimension(854, 480));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Gotham", 0, 14)); // NOI18N
        jLabel8.setText("Age : ");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 110, 30));

        jLabel11.setFont(new java.awt.Font("Gotham", 0, 14)); // NOI18N
        jLabel11.setText("Weight : ");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 110, 30));

        jLabel13.setFont(new java.awt.Font("Gotham", 0, 14)); // NOI18N
        jLabel13.setText("Gender : ");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, 110, 30));

        jLabel12.setFont(new java.awt.Font("Gotham", 0, 14)); // NOI18N
        jLabel12.setText("Height : ");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 110, 30));

        jLabel14.setFont(new java.awt.Font("Gotham", 0, 14)); // NOI18N
        jLabel14.setText("Vaccine Name : ");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, 130, 30));

        save.setFont(new java.awt.Font("Gotham Light", 1, 14)); // NOI18N
        save.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        save.setText("Save");
        save.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveMouseClicked(evt);
            }
        });
        jPanel1.add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 290, 160, 40));

        jLabel5.setFont(new java.awt.Font("Gotham", 0, 14)); // NOI18N
        jLabel5.setText("User Id : ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 90, 30));

        jLabel9.setFont(new java.awt.Font("Gotham", 0, 14)); // NOI18N
        jLabel9.setText("Mother Name : ");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 110, 30));

        jLabel10.setFont(new java.awt.Font("Gotham", 0, 14)); // NOI18N
        jLabel10.setText("Date of Birth : ");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 110, 30));

        jLabel7.setFont(new java.awt.Font("Gotham", 0, 14)); // NOI18N
        jLabel7.setText("Mail ID");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 110, 30));

        jLabel4.setFont(new java.awt.Font("Gotham Light", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/All the Images/btn white.png"))); // NOI18N
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 290, 180, 40));

        jLabel3.setFont(new java.awt.Font("Gotham", 0, 14)); // NOI18N
        jLabel3.setText("Full Name : ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 90, 30));

        jLabelMinimize1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/All the Images/min-sqr.png"))); // NOI18N
        jLabelMinimize1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMinimize1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinimize1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabelMinimize1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 10, -1, 60));

        jLabelClose1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/All the Images/close-sqr.png"))); // NOI18N
        jLabelClose1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelClose1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelClose1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabelClose1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 10, -1, 60));

        jLabel15.setFont(new java.awt.Font("Gotham", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Save the Details");
        jLabel15.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 250, 280, 40));

        goback.setFont(new java.awt.Font("Gotham Light", 1, 14)); // NOI18N
        goback.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        goback.setText("Go Back");
        goback.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        goback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gobackMouseClicked(evt);
            }
        });
        jPanel1.add(goback, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 390, 70, 40));

        goback1.setFont(new java.awt.Font("Gotham Light", 1, 14)); // NOI18N
        goback1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        goback1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/All the Images/goback.png"))); // NOI18N
        goback1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        goback1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                goback1MouseClicked(evt);
            }
        });
        jPanel1.add(goback1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 390, 60, 40));

        jLabel6.setFont(new java.awt.Font("Gotham Light", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/All the Images/btn white.png"))); // NOI18N
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 390, 180, 40));

        jLabel16.setFont(new java.awt.Font("Gotham", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Go Back to Admin Panel");
        jLabel16.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 350, 280, 40));

        childfullname.setFont(new java.awt.Font("Gotham Light", 0, 14)); // NOI18N
        childfullname.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        childfullname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                childfullnameActionPerformed(evt);
            }
        });
        jPanel1.add(childfullname, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 280, 30));

        mail_id.setFont(new java.awt.Font("Gotham Light", 0, 14)); // NOI18N
        mail_id.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        mail_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mail_idActionPerformed(evt);
            }
        });
        jPanel1.add(mail_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 280, 30));

        mothername.setFont(new java.awt.Font("Gotham Light", 0, 14)); // NOI18N
        mothername.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        mothername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mothernameActionPerformed(evt);
            }
        });
        jPanel1.add(mothername, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 280, 30));

        userid.setEditable(false);
        userid.setBackground(new java.awt.Color(255, 255, 255));
        userid.setFont(new java.awt.Font("Gotham Light", 0, 14)); // NOI18N
        userid.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        userid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                useridActionPerformed(evt);
            }
        });
        jPanel1.add(userid, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 280, 30));

        changevaccine.setBackground(new java.awt.Color(255, 0, 51));
        changevaccine.setFont(new java.awt.Font("Gotham", 0, 11)); // NOI18N
        changevaccine.setForeground(new java.awt.Color(255, 255, 255));
        changevaccine.setText("Change Here");
        changevaccine.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        changevaccine.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                changevaccineMouseClicked(evt);
            }
        });
        changevaccine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changevaccineActionPerformed(evt);
            }
        });
        jPanel1.add(changevaccine, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 380, 110, 30));

        vaccine.setEditable(false);
        vaccine.setBackground(new java.awt.Color(255, 255, 255));
        vaccine.setFont(new java.awt.Font("Gotham Light", 0, 14)); // NOI18N
        vaccine.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        vaccine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vaccineActionPerformed(evt);
            }
        });
        jPanel1.add(vaccine, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, 210, 30));

        height.setFont(new java.awt.Font("Gotham Light", 0, 14)); // NOI18N
        height.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        height.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                heightActionPerformed(evt);
            }
        });
        jPanel1.add(height, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 280, 30));

        weight.setFont(new java.awt.Font("Gotham Light", 0, 14)); // NOI18N
        weight.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        weight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weightActionPerformed(evt);
            }
        });
        jPanel1.add(weight, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 280, 30));

        age.setFont(new java.awt.Font("Gotham Light", 0, 14)); // NOI18N
        age.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageActionPerformed(evt);
            }
        });
        jPanel1.add(age, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 280, 30));

        dob.setFont(new java.awt.Font("Gotham Light", 0, 14)); // NOI18N
        dob.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        dob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dobActionPerformed(evt);
            }
        });
        jPanel1.add(dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 280, 30));

        gender.setFont(new java.awt.Font("Gotham Light", 0, 14)); // NOI18N
        gender.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        gender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderActionPerformed(evt);
            }
        });
        jPanel1.add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, 280, 30));

        changeVaccine.setFont(new java.awt.Font("Gotham", 0, 14)); // NOI18N
        changeVaccine.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vaccine Name", "BCG", "DTP 1", "DTP 2", "Hepatitis A", "MMR 1", "MMR 2", "InfluenzaOPV" }));
        changeVaccine.setBorder(null);
        changeVaccine.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        changeVaccine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeVaccineActionPerformed(evt);
            }
        });
        jPanel1.add(changeVaccine, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, 200, 30));

        jLabel1.setFont(new java.awt.Font("Gotham Medium", 0, 11)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/All the Images/editchild.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 0, 910, 480));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelMinimize1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinimize1MouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelMinimize1MouseClicked

    private void jLabelClose1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelClose1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabelClose1MouseClicked

    private void saveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveMouseClicked
        // TODO add your handling code here:
        try{
//            String childID = userid.getText();
//            String fullname = childfullname.getText();
//            String fathername1 = fathername.getText();
//            String mothername1 = mothername.getText();
//            String dob = dateofbirth.getText();
//            String age1 = age.getText();
//            String weight1 = weight.getText();
//            String height1 = height.getText();
//            String gender1 = gender.getText();
//            String vaccine1 = vaccine.getText();
            
//            String query="UPDATE `child_details` SET" 
//                    +"`child_ID`="+childID+",`child_name`="+fullname+",`father_name`="+fathername1
//                    +",`mother_name`="+mothername1+",`child_gender`="+gender1+",`child_birth`="+dob
//                    +",`child_age`="+age1+",`child_weight`="+weight1+",`child_height`="+height1
//                    +",`child_vaccines`="+vaccine1

            String query="UPDATE `child_details` SET `child_ID`=?,`child_name`=?,`mail_address`=?,"
                        +"`mother_name`=?,`child_gender`=?,`child_birth`=?"
                        +",`child_age`=?,`child_weight`=?,`child_height`=?"
                        +",`child_vaccines`=?";

            con=DriverManager.getConnection("jdbc:mysql://localhost/child e-immunization","root","");  
            pst=con.prepareStatement(query);
            pst.setString(1, userid.getText());
            pst.setString(2, childfullname.getText());
            pst.setString(3, mail_id.getText());
            pst.setString(4, mothername.getText());
            pst.setString(6, dob.getText());
            pst.setString(7, age.getText());
            pst.setString(8, weight.getText());
            pst.setString(9, height.getText());
            pst.setString(5, gender.getText());
            pst.setString(10, changeVaccine.getSelectedItem().toString());
            
            pst.execute();
            JOptionPane.showMessageDialog(this, "Details added successfully ..");
            
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_saveMouseClicked

    private void gobackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gobackMouseClicked
        AddOrSee object = new AddOrSee();
        object.pack();
        object.setVisible(true);
        object.setLocationRelativeTo(null);
        object.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_gobackMouseClicked

    private void goback1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goback1MouseClicked
        AddOrSee object = new AddOrSee();
        object.pack();
        object.setVisible(true);
        object.setLocationRelativeTo(null);
        object.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_goback1MouseClicked

    private void childfullnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_childfullnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_childfullnameActionPerformed

    private void useridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_useridActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_useridActionPerformed

    private void mail_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mail_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mail_idActionPerformed

    private void mothernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mothernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mothernameActionPerformed

    private void heightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_heightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_heightActionPerformed

    private void weightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_weightActionPerformed

    private void ageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageActionPerformed

    private void dobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dobActionPerformed

    private void genderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderActionPerformed

    private void changeVaccineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeVaccineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_changeVaccineActionPerformed

    private void changevaccineMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changevaccineMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_changevaccineMouseClicked

    private void vaccineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vaccineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vaccineActionPerformed

    private void changevaccineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changevaccineActionPerformed
        // TODO add your handling code here:
        vaccine.setVisible(false);
        changeVaccine.setVisible(true);
    }//GEN-LAST:event_changevaccineActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditChildDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditChildDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditChildDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditChildDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditChildDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField age;
    private javax.swing.JComboBox<String> changeVaccine;
    private javax.swing.JButton changevaccine;
    private javax.swing.JTextField childfullname;
    private javax.swing.JTextField dob;
    private javax.swing.JTextField gender;
    private javax.swing.JLabel goback;
    private javax.swing.JLabel goback1;
    private javax.swing.JTextField height;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelClose1;
    private javax.swing.JLabel jLabelMinimize1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField mail_id;
    private javax.swing.JTextField mothername;
    private javax.swing.JLabel save;
    private javax.swing.JTextField userid;
    private javax.swing.JTextField vaccine;
    private javax.swing.JTextField weight;
    // End of variables declaration//GEN-END:variables
}
