package javaapplication1;

import java.sql.*;
import javax.swing.JFrame;
import javax.swing.*;
import java.util.*;
import javax.mail.*;
import javax.mail.internet.*;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Faizan Ali
 */
public class ViewDetailOfChild extends javax.swing.JFrame {
    String from,to,host,sub,content;
    
    
    Connection con=null;
    Statement stmt;
//    String id = "faizan29";

    /**
     * Creates new form ViewDetailOfChild
     */
    public ViewDetailOfChild() {
            initComponents(); 
            showDetails();
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        childfullname = new javax.swing.JTextField();
        mail_id = new javax.swing.JTextField();
        dateofbirth = new javax.swing.JTextField();
        mothername = new javax.swing.JTextField();
        userid = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        age = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        weight = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        gender = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        height = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        vaccinename = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        goback1 = new javax.swing.JLabel();
        goback = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelMinimize1 = new javax.swing.JLabel();
        jLabelClose1 = new javax.swing.JLabel();
        editchild = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        sendmail = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(43, 57, 144));
        jPanel1.setPreferredSize(new java.awt.Dimension(854, 480));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        childfullname.setFont(new java.awt.Font("Gotham", 0, 14)); // NOI18N
        childfullname.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        childfullname.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        childfullname.setFocusable(false);
        childfullname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                childfullnameActionPerformed(evt);
            }
        });
        jPanel1.add(childfullname, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 260, 30));

        mail_id.setFont(new java.awt.Font("Gotham", 0, 14)); // NOI18N
        mail_id.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        mail_id.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        mail_id.setFocusable(false);
        mail_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mail_idActionPerformed(evt);
            }
        });
        jPanel1.add(mail_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 260, 30));

        dateofbirth.setFont(new java.awt.Font("Gotham", 0, 14)); // NOI18N
        dateofbirth.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        dateofbirth.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        dateofbirth.setFocusable(false);
        dateofbirth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateofbirthActionPerformed(evt);
            }
        });
        jPanel1.add(dateofbirth, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 260, 30));

        mothername.setFont(new java.awt.Font("Gotham", 0, 14)); // NOI18N
        mothername.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        mothername.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        mothername.setFocusable(false);
        mothername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mothernameActionPerformed(evt);
            }
        });
        jPanel1.add(mothername, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 260, 30));

        userid.setFont(new java.awt.Font("Gotham", 0, 14)); // NOI18N
        userid.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        userid.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        userid.setFocusable(false);
        userid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                useridActionPerformed(evt);
            }
        });
        jPanel1.add(userid, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 260, 30));

        jLabel8.setFont(new java.awt.Font("Gotham", 0, 14)); // NOI18N
        jLabel8.setText("Age : ");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 110, 30));

        age.setFont(new java.awt.Font("Gotham", 0, 14)); // NOI18N
        age.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        age.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        age.setFocusable(false);
        age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageActionPerformed(evt);
            }
        });
        jPanel1.add(age, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 260, 30));

        jLabel11.setFont(new java.awt.Font("Gotham", 0, 14)); // NOI18N
        jLabel11.setText("Weight : ");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 110, 30));

        weight.setFont(new java.awt.Font("Gotham", 0, 14)); // NOI18N
        weight.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        weight.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        weight.setFocusable(false);
        weight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weightActionPerformed(evt);
            }
        });
        jPanel1.add(weight, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 260, 30));

        jLabel13.setFont(new java.awt.Font("Gotham", 0, 14)); // NOI18N
        jLabel13.setText("Gender : ");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, 110, 30));

        gender.setFont(new java.awt.Font("Gotham", 0, 14)); // NOI18N
        gender.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        gender.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        gender.setFocusable(false);
        gender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderActionPerformed(evt);
            }
        });
        jPanel1.add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, 260, 30));

        jLabel12.setFont(new java.awt.Font("Gotham", 0, 14)); // NOI18N
        jLabel12.setText("Height : ");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 110, 30));

        height.setFont(new java.awt.Font("Gotham", 0, 14)); // NOI18N
        height.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        height.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        height.setFocusable(false);
        height.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                heightActionPerformed(evt);
            }
        });
        jPanel1.add(height, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, 260, 30));

        jLabel14.setFont(new java.awt.Font("Gotham", 0, 14)); // NOI18N
        jLabel14.setText("Vaccine Name : ");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, 130, 30));

        vaccinename.setFont(new java.awt.Font("Gotham", 0, 14)); // NOI18N
        vaccinename.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        vaccinename.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        vaccinename.setFocusable(false);
        vaccinename.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vaccinenameActionPerformed(evt);
            }
        });
        jPanel1.add(vaccinename, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, 260, 30));

        jLabel5.setFont(new java.awt.Font("Gotham", 0, 14)); // NOI18N
        jLabel5.setText("User Id : ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 90, 30));

        jLabel9.setFont(new java.awt.Font("Gotham", 0, 14)); // NOI18N
        jLabel9.setText("Mother Name : ");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 110, 30));

        jLabel10.setFont(new java.awt.Font("Gotham", 0, 14)); // NOI18N
        jLabel10.setText("Date of Birth : ");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 110, 30));

        jLabel7.setFont(new java.awt.Font("Gotham", 0, 14)); // NOI18N
        jLabel7.setText("Mail ID : ");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 110, 30));

        goback1.setFont(new java.awt.Font("Gotham Light", 1, 14)); // NOI18N
        goback1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        goback1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/All the Images/goback.png"))); // NOI18N
        goback1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        goback1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                goback1MouseClicked(evt);
            }
        });
        jPanel1.add(goback1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 390, 60, 40));

        goback.setFont(new java.awt.Font("Gotham Light", 1, 14)); // NOI18N
        goback.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        goback.setText("Go Back");
        goback.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        goback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gobackMouseClicked(evt);
            }
        });
        jPanel1.add(goback, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 390, 70, 40));

        jLabel4.setFont(new java.awt.Font("Gotham Light", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/All the Images/btn white.png"))); // NOI18N
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 390, 180, 40));

        jLabel3.setFont(new java.awt.Font("Gotham", 0, 14)); // NOI18N
        jLabel3.setText("Full Name : ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 90, 30));

        jLabelMinimize1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/All the Images/min-sqr.png"))); // NOI18N
        jLabelMinimize1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMinimize1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinimize1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabelMinimize1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 10, -1, 60));

        jLabelClose1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/All the Images/close-sqr.png"))); // NOI18N
        jLabelClose1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelClose1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelClose1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabelClose1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 10, -1, 60));

        editchild.setFont(new java.awt.Font("Gotham Light", 1, 14)); // NOI18N
        editchild.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        editchild.setText("Edit Details");
        editchild.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editchild.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editchildMouseClicked(evt);
            }
        });
        jPanel1.add(editchild, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 270, 160, 40));

        jLabel6.setFont(new java.awt.Font("Gotham Light", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/All the Images/btn white.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 270, 180, 40));

        sendmail.setFont(new java.awt.Font("Gotham Light", 1, 14)); // NOI18N
        sendmail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sendmail.setText("Send Remainder");
        sendmail.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sendmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sendmailMouseClicked(evt);
            }
        });
        jPanel1.add(sendmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 330, 160, 40));

        jLabel16.setFont(new java.awt.Font("Gotham Light", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/All the Images/btn white.png"))); // NOI18N
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 330, 180, 40));

        jLabel1.setFont(new java.awt.Font("Gotham Medium", 0, 11)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/All the Images/ChildDetails.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 0, 910, 480));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void showDetails(){
        String id = ChildSession.username;
        try{
            String query="SELECT * FROM `child_details` WHERE `child_ID`='"+id+"'";
            con = DriverManager.getConnection("jdbc:mysql://localhost/child e-immunization","root","");  
            stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery(query); 
            
            while (rs.next()) {
                    userid.setText(rs.getString(1));
                    childfullname.setText(rs.getString(2));
                    mail_id.setText(rs.getString(3));
                    mothername.setText(rs.getString(4));
                    dateofbirth.setText(rs.getString(6));
                    age.setText(rs.getString(7));
                    weight.setText(rs.getString(8));
                    height.setText(rs.getString(9));
                    gender.setText(rs.getString(5));
                    vaccinename.setText(rs.getString(10));             
            }            
            }catch(Exception ex){
                JOptionPane.showMessageDialog(null,ex);          
        }
    }
    
    private void goback1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goback1MouseClicked
        AddOrSee object = new AddOrSee();
        object.pack();
        object.setVisible(true);
        object.setLocationRelativeTo(null);
        object.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_goback1MouseClicked

    private void gobackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gobackMouseClicked
        AddOrSee object = new AddOrSee();
        object.pack();
        object.setVisible(true);
        object.setLocationRelativeTo(null);
        object.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_gobackMouseClicked

    private void childfullnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_childfullnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_childfullnameActionPerformed

    private void mail_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mail_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mail_idActionPerformed

    private void dateofbirthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateofbirthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateofbirthActionPerformed

    private void mothernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mothernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mothernameActionPerformed

    private void useridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_useridActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_useridActionPerformed

    private void ageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageActionPerformed

    private void weightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_weightActionPerformed

    private void heightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_heightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_heightActionPerformed

    private void genderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderActionPerformed

    private void vaccinenameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vaccinenameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vaccinenameActionPerformed

    private void jLabelMinimize1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinimize1MouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelMinimize1MouseClicked

    private void jLabelClose1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelClose1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabelClose1MouseClicked

    private void editchildMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editchildMouseClicked
        EditChildDetails object = new EditChildDetails();
        object.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_editchildMouseClicked

    private void sendmailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sendmailMouseClicked
        // TODO add your handling code here:
        from = "aymanjaveriya1@gmail.com";
        to = mail_id.getText();
        host = "localhost";
        sub = "Vaccination Reminder";
        content = "Tomarrow is vaccination day of your child.Visit to vaccination center near your area so that your child will get vaccinated on time";
        
        Properties p = new Properties();
        p.put("mail.smtp.auth","true");
        p.put("mail.smtp.starttls.enable","true");
        p.put("mail.smtp.host","smtp.gmail.com");
        p.put("mail.smtp.port","587");
        
        Session s;
        s = Session.getDefaultInstance(p,new javax.mail.Authenticator(){
            protected PasswordAuthentication getPasswordAuthentication()
            {
                return new PasswordAuthentication("aymanjaveriya1@gmail.com","mana@2008");//remove before share
            }
            
        });
        
        try{
            MimeMessage m = new MimeMessage(s);
            m.setFrom(from);
            m.addRecipient(Message.RecipientType.TO, new InternetAddress(to));
            m.setSubject(sub);
            m.setText(content);
            Transport.send(m);
            System.out.println("Sucessfull....");    
        }
        catch(Exception e)
        {
            e.printStackTrace();
            
        }
        
        
        
    }//GEN-LAST:event_sendmailMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewDetailOfChild.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewDetailOfChild.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewDetailOfChild.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewDetailOfChild.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewDetailOfChild().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField age;
    private javax.swing.JTextField childfullname;
    private javax.swing.JTextField dateofbirth;
    private javax.swing.JLabel editchild;
    private javax.swing.JTextField gender;
    private javax.swing.JLabel goback;
    private javax.swing.JLabel goback1;
    private javax.swing.JTextField height;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelClose1;
    private javax.swing.JLabel jLabelMinimize1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField mail_id;
    private javax.swing.JTextField mothername;
    private javax.swing.JLabel sendmail;
    private javax.swing.JTextField userid;
    private javax.swing.JTextField vaccinename;
    private javax.swing.JTextField weight;
    // End of variables declaration//GEN-END:variables
}
